// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmG_VNVgPJK4wKc3kAV0_H1nDjHQ311aw',
    appId: '1:1040146784841:web:85e15671da8c32f6235598',
    messagingSenderId: '1040146784841',
    projectId: 'cmsc23-todo-app-jacarranza',
    authDomain: 'cmsc23-todo-app-jacarranza.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jacarranza.appspot.com',
    measurementId: 'G-X67CFV03TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dT9SnyrOzAv2xcVx1JJDA9jf0-37geM',
    appId: '1:1040146784841:android:6e2211cef8da03f8235598',
    messagingSenderId: '1040146784841',
    projectId: 'cmsc23-todo-app-jacarranza',
    storageBucket: 'cmsc23-todo-app-jacarranza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9xaXS5l6QbwKRoe0fplvPep-FDgE4uc',
    appId: '1:1040146784841:ios:9ed3e9e6cefe83a9235598',
    messagingSenderId: '1040146784841',
    projectId: 'cmsc23-todo-app-jacarranza',
    storageBucket: 'cmsc23-todo-app-jacarranza.appspot.com',
    iosClientId: '1040146784841-2mvertgbgs3b2tdblid9d69dd3tdllqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9xaXS5l6QbwKRoe0fplvPep-FDgE4uc',
    appId: '1:1040146784841:ios:9ed3e9e6cefe83a9235598',
    messagingSenderId: '1040146784841',
    projectId: 'cmsc23-todo-app-jacarranza',
    storageBucket: 'cmsc23-todo-app-jacarranza.appspot.com',
    iosClientId: '1040146784841-2mvertgbgs3b2tdblid9d69dd3tdllqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
