// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-W4Osw1e5DlQW2pOpB6IDfJSxhNPz24',
    appId: '1:974813067056:web:431c13cae4de254493baf5',
    messagingSenderId: '974813067056',
    projectId: 'exercise6-carranza',
    authDomain: 'exercise6-carranza.firebaseapp.com',
    storageBucket: 'exercise6-carranza.appspot.com',
    measurementId: 'G-DKPH317BE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEXn97HwkssJ-Tzs-7P30j7AoE8_Lxwo',
    appId: '1:974813067056:android:beb0750e0a47ee9e93baf5',
    messagingSenderId: '974813067056',
    projectId: 'exercise6-carranza',
    storageBucket: 'exercise6-carranza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOawwvA7rDnzLGCcHLkSD2XpdTnT00BqE',
    appId: '1:974813067056:ios:9574d539ac66016593baf5',
    messagingSenderId: '974813067056',
    projectId: 'exercise6-carranza',
    storageBucket: 'exercise6-carranza.appspot.com',
    iosClientId: '974813067056-4lsq2qt9kmll6gp881o8hlltvq07meme.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOawwvA7rDnzLGCcHLkSD2XpdTnT00BqE',
    appId: '1:974813067056:ios:9574d539ac66016593baf5',
    messagingSenderId: '974813067056',
    projectId: 'exercise6-carranza',
    storageBucket: 'exercise6-carranza.appspot.com',
    iosClientId: '974813067056-4lsq2qt9kmll6gp881o8hlltvq07meme.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}


